### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/z3c.authviewlet#7]
It no longer builds due to missing deps that have dropped support for it.

https://travis-ci.org/github/zopefoundation/z3c.authviewlet/jobs/665305304

**Comment by mgedmin** [comment]
I, uh, accidentally pushed to master instead of creating a branch for this change.

https://github.com/zopefoundation/z3c.authviewlet/commit/69553756c0e8e177aced9ef402ce0805e7b5a686

Now I'm too lazy to revert and create a proper PR, unless somebody tells me I ought to.

(The diff is trivial, and a local tox run shows no tests ought to break.)
